### ISSUE TITLE
Trying to start new config or edit old one returns Server 500 error

### ISSUE THREAD

**Issue by Popolechien** [offspot/cardshop#306]
![Capture d’écran 2022-12-16 à 17 50 19](https://user-images.githubusercontent.com/21675885/208148373-fb67275d-9d23-4359-9068-c944326d5ce3.png)

**Comment by rgaudin** [comment]
This is due to a ZIM with incorrect metadata in the library.

```yaml
coopmaths.:
    description: "Ressources libres pour la personnalisation des apprentissages en
      math\xE9matiques"
    id: 2081f380-2241-91ea-3b9e-b17b9538cdd7
    langid: coopmaths.
    language: ''
    name: Coopmaths
    sha256sum: e63ca2d238464c7dff7f9f721614d823d2fcb7ee5803268dd8461d5b8f304a13
    size: 393975808
    sw: y
    type: zim
    url: http://download.kiwix.org/zim/zimit/coopmaths_2022-12.zim
    version: '2022-12-13'
```

- http://download.kiwix.org/zim/zimit/coopmaths_2022-12.zim has no Language metadata.
- Code assumes there is always a Language metadata.
- Code (borrowed from hotspot) should be more flexible and ignore such entries. Not sure we should create a ticket as this will change both at hotspot and cardshop levele soon.
- Removed ZIM file ; problem fixed for now.
- Will check with zimit as we should not end up with a ZIM without Language. Actually I think the ZIM might have had an incorrect `Language` and the library/ideascube gen script might have removed it because it was not correct.
- Should we pause zimfarm recipes operations until we have a formal, validated training for users and maybe implement a couple protections in the code ?
